### ISSUE TITLE
[Feature Request] Option to teleport players to a random location when entering the void dimension

### ISSUE THREAD

**Issue by elhertz** [nanite/JAVD#1]
### Feature Description

I'd like to give my players a way to have a "pocket" dimension of sorts but I don't want to have multiple worlds loaded at once. 
So an alternative came to mind: assign each player a random location (or do it like skyblock and just space them out evenly). That way there's only one world loaded and everyone gets their "pocket dimension" without impacting the server that much.
Hope you like the idea. Thank you for the mod!

**Comment by UnRealDinnerbone** [comment]
Not going to add this, as the way teleporting work finds a spot near the same cords the player is in. random cords would make the mod complex when this is supposed to just be a simple mining dimension mod
