### ISSUE TITLE
[Issue] "Ghost" portal appears above real portal, giving away location

### ISSUE THREAD

**Issue by LuciusV** [nanite/JAVD#14]
### Minecraft Version

1.19.2

### Modloader

forge 43.2.14

### Mod version

4.0.1-build.2+mc1.19.2

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

n/a

### Steps to reproduce the issue

I place portal on overworld at (X,Z) y=35. 
When I use it, I go to void dimension, y = 128
Then when I visit (X,Z) in overworld, I can see new "teleport" block appear at (X,Z) y=128. I can stand on it, but interaction with it makes it disappear. Original portal at y=35 remains intact and fully functional.

### Description of the issue you are having

Ghost block should not appear, also in multiplayer it can reveal position of bases to pther players.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
This is a minecraft bug
