### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Veydiz** [nanite/JAVD#17]
### Minecraft Version

1.18.2

### Modloader

forge 40.2.10

### Mod version

JAVD-3.0.0-build.54

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

tconstruct:mineable/pickadze : error tag

### Steps to reproduce the issue

Look at the Void Portal tags (block & item)

### Description of the issue you are having

There's a typo in the tag tconstruct:mineable/pickaxe for the block and item VOID PORTAL.
As a result, it is not possible to mine the VOID PORTAL with a Tconstruct mod pickaxe.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Not my issue
