### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Vadewolf** [nanite/JAVD#19]
### Minecraft Version

1.20.1

### Modloader

forge 47.2.20

### Mod version

5.0.1 forge 1.20.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/JAVD/files/14075025/latest.log)

idk how this will help cause latest shows no issues

### Description of the issue you are having

if i remove the mod or trenzalore it causes my save to get errors and wont even load unless i re add the mods back

### Information

- [X] I have provided as much information as possible

**Comment by Vadewolf** [comment]
i removed the mod and lost my world due to this mod corrupting it so will never be using this mod again if it forces the player to keep the mod because of it force changing stuff it shouldnt

**Comment by UnRealDinnerbone** [comment]
1. Removing Mods always has a chance to corrupt your worlds.
2. The reason it broke is because of the way minecraft handles dimensions now. This not something I can fix

**Comment by Vadewolf** [comment]
u could fix it by not forcing ure mod changes to dimensions that u shouldnt control when all u offer is a void dimension

**Comment by UnRealDinnerbone** [comment]
I don't change anything in other dimensions?

**Comment by Vadewolf** [comment]
then pls explain how ure mod corrupted my save when i had it in the game worked but i removed it and got the crash above and nothing loaded outside of vanilla to fix and i was forced to restart due to ure mod pls

**Comment by UnRealDinnerbone** [comment]
Like I said it an issue in the vanilla that causes worlds to break, when you remove mods that add world gen / biomes
