### ISSUE TITLE
[Issue] "Unable to find javd:void world"

### ISSUE THREAD

**Issue by erwin1234777** [nanite/JAVD#2]
### Mod version

javd-forge-4.0.1-build.2+mc1.19.2.jar

### Forge mod loader version

Forge 43.1.52

### Repeatable?

- [X] Yes

### Link to log files

https://gist.github.com/erwin1234777/f954591601c72bf9592f4d36c4b621fa

### Steps to reproduce the issue

1. Make a new World.
2. Spawn in the Void portal
3. Right click it with ender pearl and then again.
4. Error at the bottom 
![javaw_jdUgitq69u](https://user-images.githubusercontent.com/29512349/202057643-77e73c1c-19f0-45bb-afc7-bd1cf19573a4.png)

### Description of the issue you are having

Cannot load the world. This is a freshly created world, with other mods.

Modlist:

[mods.txt](https://github.com/nanite/JAVD/files/10017221/files.txt)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Not my issue, it Terra Blender https://github.com/Glitchfiend/TerraBlender/issues/94
