### ISSUE TITLE
[Issue] JAGS mod uploaded to JAVD's curseforge page.

### ISSUE THREAD

**Issue by Gbergz** [nanite/JAVD#22]
### Minecraft Version

1.21

### Modloader

NeoForge 21.0.97

### Mod version

jags-neo21.0.0+mc1.21

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

none

### Steps to reproduce the issue

Download latest file, JAGS mod gets downloaded instead.

### Description of the issue you are having

![ss](https://github.com/user-attachments/assets/2133ef43-03ac-47ea-8e5a-0127efc5377a)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Fixed
