### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by AdmiralAlpaca** [nanite/JAVD#4]
### Feature Description

If possible could you please port the config to 1.19.2? It would be amazing to give every player on my server the capability of having their own personal dimension that you basically need to skyblock to create and you can customize it in it's entirety, it would also help if the dimension saved everytime I got finished with it in survival. I thought it would persist and built quite the island and stored all my items. After I logged out and came back, everything was gone....

**Comment by UnRealDinnerbone** [comment]
I do not plan on adding per player dimension support to the newer versions of this mod
