### ISSUE TITLE
[Feature Request] Spawn Platform Height and Daytime Cycle

### ISSUE THREAD

**Issue by LarcekGiglamesh** [nanite/JAVD#6]
### Feature Description

Running: 
JAVD-3.0.0-build.54+mc1.18.2
Forge 1.18.2 - 40.2.1

finally a void world for 1.18.2 i thought but when i actually tried it, i encountered these 2 issues making it hard to enjoy the void world. the plattform is generated at Y:-63 so you cannot place even a single block below the portal and without a daytime cycle, you'll never encounter hostiles unless you make a dark room, which i have yet to test. 

as such i'd like the config to be expaned to at least these 2 options:
• define platform Y position
• globally enable/disable daytime cycle for the dimension

cheers

**Comment by UnRealDinnerbone** [comment]
The y position change was done in a newer version of the mod
The daytime cycle can be done with a datapack
