### ISSUE TITLE
[Issue]Zombie attack me interdimensional when I enter the void

### ISSUE THREAD

**Issue by rtxyd** [nanite/JAVD#8]
### Minecraft Version

1.19.2

### Modloader

43.2.6

### Mod version

4.0.1

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/JAVD/files/10966311/latest.log)

### Steps to reproduce the issue

1、first place a void portal block on the ground and enter once.
2、find up another void portal block it generate in sky, and set a platform, put some zombie. 
1、make the chunk where you enter the void keep loaded(I encounter the problem in multiplayer)
2、enter the void when zombie target you.

### Description of the issue you are having

if the chunk you enter the void keep loaded, and enter the void when monster target you, the monster will still damage you when you are in the void dimension. I encounter this issue in my modpack that zombie keeps attack me from outside, not just once. Below is the test scene.
![QQ录屏20230314164635 mp4_20230314_165920](https://user-images.githubusercontent.com/65117312/224949209-cf79975f-b8a4-472f-9166-f2cbf5129099.gif)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
I believe the issue is that they attack you before you finish teleporting, and you just can't see that on the client with the world loading screen
