### ISSUE TITLE
can't leave the dimension and crashes mc

### ISSUE THREAD

**Issue by arhp777** [nanite/JAVD#9]
### Minecraft Version

1.19.2

### Modloader

forge 43.2.7

### Mod version

javd-forge-4.0.1-build.2+mc1.19.2

### Repeatable?

- [X] Yes

### Link to log files

[crash-2023-03-28_22.15.25-server.txt](https://github.com/nanite/JAVD/files/11093854/crash-2023-03-28_22.15.25-server.txt)
[debug.log](https://github.com/nanite/JAVD/files/11093857/debug.log)
[latest.log](https://github.com/nanite/JAVD/files/11093859/latest.log)

### Description of the issue you are having

when I am thing to leave the dimension and crashes mc

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
This crash does not seem like it from my mod. Some mod is breaking code elsewhere
